import type { NewsItem } from "./news-types";

// Mock seed data — folosit ca fallback / cache inițial.
// Aceste știri sunt reprezentative pentru tipul de conținut financiar
// pe care îl agregăm de la Reuters / Bloomberg / Yahoo Finance.
export const SEED_NEWS: NewsItem[] = [
  {
    id: "fed-pause-2026-01",
    title: "Fed semnalează o pauză prelungită în reducerile de dobândă pe fondul inflației persistente",
    source: "Reuters",
    url: "https://www.reuters.com/markets/us/fed-rates-2026/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    summary:
      "Procesul-verbal FOMC arată că majoritatea membrilor preferă menținerea dobânzii la nivelul actual până când inflația de bază scade sub 2.5% pentru cel puțin trei luni consecutive.",
    themes: ["banci-centrale", "macro", "obligatiuni"],
    impact: "high",
    sentiment: "negative",
    regions: ["SUA", "Global"],
    markets: ["equities", "bonds", "FX"],
    sectors: ["bănci", "real estate", "tech"],
    relevanceScore: 94,
  },
  {
    id: "nvda-earnings-q4",
    title: "Nvidia depășește estimările cu 12% pe segmentul data center; ghidaj forward conservator",
    source: "Bloomberg",
    url: "https://www.bloomberg.com/news/nvda-q4-earnings",
    publishedAt: new Date(Date.now() - 1000 * 60 * 47).toISOString(),
    summary:
      "Veniturile data center au atins 38.5 mld. USD în trimestru, dar conducerea a moderat așteptările pentru trimestrul următor citând constrângeri de aprovizionare HBM.",
    themes: ["earnings", "actiuni"],
    impact: "high",
    sentiment: "mixed",
    regions: ["SUA", "Global"],
    markets: ["equities"],
    sectors: ["tech", "semiconductoare"],
    relevanceScore: 91,
  },
  {
    id: "ecb-cut-2026",
    title: "BCE reduce dobânda cu 25 bp; Lagarde lasă deschisă opțiunea unei noi tăieri în martie",
    source: "Reuters",
    url: "https://www.reuters.com/markets/europe/ecb-rate-cut/",
    publishedAt: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
    summary:
      "Banca Centrală Europeană a redus rata depozitelor la 2.25%. Lagarde a subliniat dezinflația progresivă din zona euro, dar a evitat să se angajeze ferm pentru martie.",
    themes: ["banci-centrale", "macro", "forex"],
    impact: "high",
    sentiment: "positive",
    regions: ["Europa"],
    markets: ["bonds", "FX", "equities"],
    sectors: ["bănci", "industrie"],
    relevanceScore: 89,
  },
  {
    id: "oil-opec-cut",
    title: "OPEC+ extinde reducerile voluntare de producție până în Q3, petrolul urcă peste 84$",
    source: "Bloomberg",
    url: "https://www.bloomberg.com/news/opec-extension",
    publishedAt: new Date(Date.now() - 1000 * 60 * 130).toISOString(),
    summary:
      "Arabia Saudită și Rusia conduc extinderea reducerilor voluntare de 2.2 mil. barili/zi. Brent a depășit 84 USD pentru prima dată în șase luni.",
    themes: ["marfuri", "geopolitica", "macro"],
    impact: "high",
    sentiment: "mixed",
    regions: ["Global"],
    markets: ["commodities", "equities", "FX"],
    sectors: ["energie", "transport"],
    relevanceScore: 86,
  },
  {
    id: "china-stimulus",
    title: "China anunță un nou pachet fiscal de 1 trilion yuani pentru infrastructură și consum",
    source: "Reuters",
    url: "https://www.reuters.com/world/china/stimulus-package",
    publishedAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    summary:
      "Pachetul vizează stimularea cererii interne și sprijinirea sectorului imobiliar. Indicii din Hong Kong și Shanghai au reacționat pozitiv în deschidere.",
    themes: ["macro", "geopolitica", "actiuni"],
    impact: "high",
    sentiment: "positive",
    regions: ["Asia", "Emergente"],
    markets: ["equities", "commodities", "FX"],
    sectors: ["materiale", "industrie", "consum"],
    relevanceScore: 84,
  },
  {
    id: "yields-10y",
    title: "Randamentul Treasury 10Y revine sub 4.2% după date slabe ale comenzilor de bunuri durabile",
    source: "Yahoo Finance",
    url: "https://finance.yahoo.com/news/treasury-yields",
    publishedAt: new Date(Date.now() - 1000 * 60 * 220).toISOString(),
    summary:
      "Comenzile de bunuri durabile au scăzut cu 1.8% în luna precedentă, peste estimările de -0.5%. Investitorii reduc așteptările privind creșterea pe T1.",
    themes: ["macro", "obligatiuni"],
    impact: "medium",
    sentiment: "mixed",
    regions: ["SUA"],
    markets: ["bonds", "equities"],
    relevanceScore: 76,
  },
  {
    id: "btc-etf-flows",
    title: "Intrările record în ETF-urile Bitcoin spot duc BTC peste 105.000$",
    source: "Bloomberg",
    url: "https://www.bloomberg.com/news/btc-etf-flows",
    publishedAt: new Date(Date.now() - 1000 * 60 * 280).toISOString(),
    summary:
      "Cele 11 ETF-uri spot au atras 2.3 mld. USD în ultima săptămână. BlackRock IBIT conduce intrările cu o cotă de 47%.",
    themes: ["crypto"],
    impact: "medium",
    sentiment: "positive",
    regions: ["Global"],
    markets: ["crypto", "equities"],
    relevanceScore: 68,
  },
  {
    id: "boj-pivot",
    title: "BoJ semnalează o posibilă creștere a dobânzii în iulie; yenul se apreciază 1.2%",
    source: "Reuters",
    url: "https://www.reuters.com/markets/asia/boj-pivot",
    publishedAt: new Date(Date.now() - 1000 * 60 * 340).toISOString(),
    summary:
      "Guvernatorul Ueda a indicat că normalizarea politicii monetare poate continua dacă inflația rămâne aproape de țintă. USD/JPY a scăzut la 149.40.",
    themes: ["banci-centrale", "forex", "macro"],
    impact: "high",
    sentiment: "mixed",
    regions: ["Asia", "Global"],
    markets: ["FX", "bonds", "equities"],
    sectors: ["bănci", "export"],
    relevanceScore: 82,
  },
  {
    id: "tsla-delivery",
    title: "Tesla raportează livrări trimestriale sub estimări; presiune pe marja brută auto",
    source: "Yahoo Finance",
    url: "https://finance.yahoo.com/news/tsla-deliveries",
    publishedAt: new Date(Date.now() - 1000 * 60 * 410).toISOString(),
    summary:
      "Livrările au atins 462.000 vehicule, sub estimările de 478.000. Acțiunea a scăzut 4.8% în pre-market.",
    themes: ["earnings", "actiuni"],
    impact: "medium",
    sentiment: "negative",
    regions: ["SUA", "Global"],
    markets: ["equities"],
    sectors: ["auto", "tech"],
    relevanceScore: 64,
  },
  {
    id: "geopolitics-mideast",
    title: "Tensiunile din Marea Roșie afectează rutele comerciale; primele de risc pentru petrol cresc",
    source: "Reuters",
    url: "https://www.reuters.com/world/middle-east/red-sea",
    publishedAt: new Date(Date.now() - 1000 * 60 * 480).toISOString(),
    summary:
      "Companiile de transport maritim major rerutează prin Capul Bunei Speranțe, adăugând 10-14 zile la timpul de tranzit Asia-Europa.",
    themes: ["geopolitica", "marfuri", "macro"],
    impact: "medium",
    sentiment: "negative",
    regions: ["Global", "Europa", "Asia"],
    markets: ["commodities", "equities", "FX"],
    sectors: ["transport", "energie", "retail"],
    relevanceScore: 71,
  },
  {
    id: "eur-usd-parity",
    title: "EUR/USD testează 1.05 pe divergența politicilor monetare Fed-BCE",
    source: "Bloomberg",
    url: "https://www.bloomberg.com/news/eurusd-parity",
    publishedAt: new Date(Date.now() - 1000 * 60 * 540).toISOString(),
    summary:
      "Diferențialul de randament între Treasury și Bund 10Y se lărgește la 200 bp, presând euro în jos.",
    themes: ["forex", "banci-centrale"],
    impact: "medium",
    sentiment: "mixed",
    regions: ["Europa", "SUA"],
    markets: ["FX", "bonds"],
    relevanceScore: 67,
  },
  {
    id: "jpm-earnings",
    title: "JPMorgan depășește estimările pe trading; dobânda netă rămâne stabilă",
    source: "Yahoo Finance",
    url: "https://finance.yahoo.com/news/jpm-earnings",
    publishedAt: new Date(Date.now() - 1000 * 60 * 620).toISOString(),
    summary:
      "Veniturile din trading FICC au crescut 21% YoY. Dimon avertizează asupra incertitudinilor geopolitice persistente.",
    themes: ["earnings", "actiuni"],
    impact: "medium",
    sentiment: "positive",
    regions: ["SUA", "Global"],
    markets: ["equities"],
    sectors: ["bănci"],
    relevanceScore: 72,
  },
];
